function E = TangentModulusReinf(R,b,strain,strain_0,stress_0,strain_r,stress_r)
%TANGENTMODULUSREINF
%    E = TANGENTMODULUSREINF(R,B,STRAIN,STRAIN_0,STRESS_0,STRAIN_R,STRESS_R)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    17-Apr-2018 22:25:31

t2 = strain_0-strain_r;
t3 = 1.0./t2;
t4 = strain-strain_r;
t5 = t3.*t4;
t6 = t5.^R;
t7 = t6+1.0;
t8 = 1.0./R;
t9 = b-1.0;
E = (stress_0-stress_r).*(b.*t3-t3.*t7.^(-t8).*t9+1.0./t2.^2.*t4.*t5.^(R-1.0).*t7.^(-t8-1.0).*t9);
