function E = TangentModulusConcBackbone2(Z,fc,strain)
%TANGENTMODULUSCONCBACKBONE2
%    E = TANGENTMODULUSCONCBACKBONE2(Z,FC,STRAIN)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Apr-2018 14:32:19

E = -Z.*fc.*sign(strain);
