function E = TangentModulusConcBackbone1(fc,strain,strain_0)
%TANGENTMODULUSCONCBACKBONE
%    E = TANGENTMODULUSCONCBACKBONE(FC,STRAIN,STRAIN_0)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Apr-2018 14:29:36

E = fc.*1.0./strain_0.^2.*(strain-strain_0).*-2.0;
